### ISSUE TITLE
Error in PAT EDAPT report

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-PAT#111] opened 2019-05-10 17:28 UTC
https://unmethours.com/question/38681/xml-creator-broken-in-pat-280/

Unclear if this is a PAT, reporting measure, OpenStudio, or E+ issue

**Comment by macumber** [comment] 2019-05-17 16:31
@kflemin can you look into this and try to diagnose where the issue is?

**Comment by kflemin** [comment] 2019-05-17 16:42
@macumber, this should be assigned to @asparke2. He suspects that something's changed in an energyplus query and that the issue fix has to happen in the measure itself.

**Comment by macumber** [comment] 2019-05-17 17:46
Thanks @kflemin, @asparke2 can you look into this early next week?  We want to have issues ready for 2.8.1 by next Friday.

**Comment by asparke2** [comment] 2019-05-17 19:57
Pretty sure this was caused by a timeseries data change in E+.  Will keep investigating.

Model in 2.7.1
![image](https://user-images.githubusercontent.com/2009290/57952793-76d63000-78ab-11e9-8bcd-3d8d05f7365b.png)

Same model converted to 2.8.0
![image](https://user-images.githubusercontent.com/2009290/57952828-8e151d80-78ab-11e9-9d9f-92a1e7dca659.png)

**Comment by asparke2** [comment] 2019-05-18 02:50
Ok, it appears that between EnergyPlus 9.0 and 9.1 the Year and Day of Week fields in the timeseries outputs were fixed.  See screenshot below showing a 9.0 and a 9.1 file where the start year was set to 2006 and start day of week is Sunday.

![image](https://user-images.githubusercontent.com/2009290/57963525-86bd3680-78e2-11e9-81c7-48dcc8d094a6.png)

Then see comparison of the first few timesteps in sql timeseries below.  In 2.7.1, the DateTime says Thursday 2009 (which does not match IDF file), but the EnergyPlus DayType timeseries has a 1 (Sunday), which means that the simulation itself was starting on a Sunday, but the sql timeseries dates didn't match.

```
OS 2.7.1 (E+ 9.0)
# First timestep datetime:
Thursday, 2009-Jan-01 at 00:10:00
EnergyPlus DayType of first day = 1 (1 = Sunday)
9.10537391028085kW; 2009-Jan-01; 00:10:00; Thursday
9.805175394686607kW; 2009-Jan-01; 00:20:00; Thursday
10.62333673383317kW; 2009-Jan-01; 00:30:00; Thursday
```

Contrast that with the output from 2.8.0 below. The DateTime says Sunday 2006, which now matches the IDF file and the EnergyPlus DayType of 1 (Sunday).

```
OS 2.8.0 (E+ 9.1)
# First timestep datetime:
Sunday, 2006-Jan-01 at 00:10:00
EnergyPlus DayType = 1 (1 = Sunday)
9.893356208441505kW; 2006-Jan-01; 00:10:00; Sunday
10.636266349833171kW; 2006-Jan-01; 00:20:00; Sunday
10.636266349833171kW; 2006-Jan-01; 00:30:00; Sunday
```

Because the Year in the sql query was previously always 2009 and the days of week were wrong, the XcelEDAReportingandQAQC measure was using 2009 when creating dates for comparison against the sql file and using the DayTypes timeseries (which was correct) to check the day of week.

# Solution
Now that the sql timeseries actually reflects the correct year, the XcelEDAReportingandQAQC measure needs to have version-specific logic to extract the Year from the sql file and use that when creating the dates for comparison.  Good news is that nothing inside OS or E+ or PAT should need to change.

**Closed as completed** 2019-06-12 17:22 UTC
