### ISSUE TITLE
Can't download measures from BCL on mac version of PAT

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#104] opened 2018-12-21 17:37 UTC
I tested in 2.7.1, 2.7.0, 2.4.0. @asparke2 confirmed it worked on windows @carlobianchi89 also could not download on mac. I don't have any issue downloading through the OS app. This issue occurs on any measure, not just specific measure or type of measure.

![screen shot 2018-12-21 at 10 10 12 am](https://user-images.githubusercontent.com/4857055/50355489-216c4180-050c-11e9-9102-c7e346e6e8d6.png)

What is interesting, is that Carlo is seeing this dialog that I don't get.

<img width="1676" alt="screen shot 2018-12-21 at 10 18 50 am" src="https://user-images.githubusercontent.com/4857055/50355546-4d87c280-050c-11e9-8555-c41079adbca0.png">

**Comment by DavidGoldwasser** [comment] 2018-12-21 17:52
When I tried 2.7.2 I was able to see the yellow "!" in top right and open the same dialog Carlo saw.

**Comment by kflemin** [comment] 2019-03-05 20:53
This is not a bug in PAT itself.  Best guess is that this is due to outdated openssl version within the OpenStudio package for mac.  Awaiting an updated installed to test.

**Comment by macumber** [comment] 2019-03-08 18:08
Closing here

**Closed as completed by macumber** 2019-03-08 18:08 UTC
Labels: severity - Major Bug
